### ISSUE TITLE
Insufficient performance compared to the paper

### ISSUE THREAD

**Issue by KojiTakeda00** [vdorbala/LGX#2]
I tried inference using the ROBOTHOR dataset, but the performance is not good enough.
What I tried was changing the parameters as described in the paper. But the performance is still not good.
Overall SR - 0.2788888888888889
Overall SPL - 0.07730374592660717
Overall PSR - 70.46829781636411

The parameters I used are below.
HEIGHT = 512 # Image frame height
WIDTH = 512 # Image frame width
STEP_SIZE = 5 # How many times must the agent RIP with the LLM in a single episode.
FOV = 60 # Field of View.
RIP_RESOLUTION = 30 # Rotate in Place resolution.
ROT_TIMEGAP = 0.001 # Sleep time between rotations.
FORWARD_DIST = 6 # For the path planner, how many meters ahead should the agent go to explore?
LOCKED_FORWARD_DIST = 2 # How many meters should the planner plan a path for after finding the target. Irrelavant for OSR.
LOCKED_STEPS = 3 # Number of steps to move forward after target locking takes place.
FORWARD_STEPS = 5 # Brute force alternate to move forward in Thor, if move_base fails to find a feasible path.
TARGET_DIST = 2 # Target distance threshold for determining success.
PATH_FITTING_THRESHOLD = 5 # In meters. For fitting ROS plan poses to Thor's positions. Higher value translates to more inflation/cushion space.
GLIP_THRESHOLD = 0.85 # Threshold for accepting GLIP's predictions.
EPISODE_SKIP = -1 # Number of Thor episodes to skip.
VISIBILITY_DIST = 20 # Thor's visiblity distance.
HALLWAY_CHECK = False # True, if the word "hallway" should be added to the detected object list.
START_CURRENT = True # True, if episode runs need to be started where it left off.
LAVIS_PASS = False # Set either this or YOLO_PASS to be True.
YOLO_PASS = True # Set either this or LAVIS_PASS to be True.

Should I change somewhere to reproduce same result shown in the original paper?
Thanks.

**Comment by vdorbala** [comment]
Overall performance is very sensitive to the performance of the LLM and the GLIP threshold.

What version of GPT are you using? We observed significant variance during each run, and the paper reports the best values. We used text-davinci-003 in the implementation, which seems to be a legacy model now.

**Comment by KojiTakeda00** [comment]
Thank you for your reply.

I experimented 3 times with text-davinci-003 and the performance was similar and not good enough.

I experimented with the following values as described in the code when using GPT3, should I change them?
temperature=0.7,
max_tokens=50,
top_p=1,
frequency_penalty=0.2,
presence_penalty=0

**Comment by vdorbala** [comment]
The performance is not deterministic and is sensitive to what GPT predicts at each timestep. Moreover, text-davinci-003 is a legacy model now, and poor performance may be a result of OpenAI not supporting this model anymore. You could try using GPT-4, their latest model. As mentioned earlier, we present the best results that we obtained in the paper (which ranged from ~29% to the 35% SR reported). The main novelty of the work was to present a way to integrate LLMs for zero-shot ObjectNav --- a perfect reproduction may never be possible due to GPT's blackbox nature.

Also, [here](https://arxiv.org/pdf/2301.13166.pdf) is a very similar paper that came out around the same time which used ChatGPT (presumably with text-davinci-003 as backend) in a similar manner. They report similar performance (if not better) to ours (39% SR), if you'd like to replicate it for verification purposes.
